### ISSUE TITLE
Add change(s) from Equicord

### ISSUE THREAD

**Issue by RobinRMC** [Kyuuhachi/VencordPlugins#10]
Equicord/Equicord@dd05fb1d06361f0d7dee91578ab25e9a997a0ac2

\+ maybe some changes made to other plugins

**Comment by Kyuuhachi** [comment]
Why should I care what some random weirdo fork does?

**Comment by RobinRMC** [comment]
> Why should I care what some random weirdo fork does?

Because they're good changes.
