### ISSUE TITLE
DeadMembers crashing on forum channel

### ISSUE THREAD

**Issue by Roki100** [Kyuuhachi/VencordPlugins#5]
yes
![image](https://github.com/Kyuuhachi/VencordPlugins/assets/35699619/6c1e8151-59fe-42a0-80a1-22dba381fdd9)

**Comment by Kyuuhachi** [comment]
Could you provide some more detail? I can't reproduce from only this.

**Comment by Roki100** [comment]
> Could you provide some more detail? I can't reproduce from only this.

what excatly? my client instantly crashes when i open a forum channel with the plugin enabled

**Comment by Roki100** [comment]
if you want you could try seeing it on your end, as i also crash on a forum channel in notsoserver: https://discord.com/invite/9Ukuw9V
support-forums channel - opening it crashes my client just like the other channel that got me to open this issue, disabling the plugin solves the issue

**Comment by Kyuuhachi** [comment]
I browsed through a couple other forum channels I have access to and was able to confirm the crash. I have no idea *why* it crashes, but this should solve it.

**Comment by Binerax** [comment]
I believe this problem has returned? Hard to get a debug as I cannot recreate it consistently but opening forum channel sometimes crashes. If I can actually recreate consistently I will update.

**Comment by Binerax** [comment]
![Discord_Jv0Esj7xVN](https://github.com/Kyuuhachi/VencordPlugins/assets/161184100/ff6dda32-4bf6-4d72-ad31-a69123ae59fe)
