### ISSUE TITLE
Deadmembers crashes when using Message Logger Enhanced.

### ISSUE THREAD

**Issue by Binerax** [Kyuuhachi/VencordPlugins#6]
Same as title. Crashes when trying to open log in [message logger enhanced](https://github.com/Syncxv/vc-message-logger-enhanced)

**Comment by Kyuuhachi** [comment]
I can see how that one might conflict, but there's little I can do without more information. Some information about the crash would be helpful, such as the error message itself, backtrace (preferably from a dev build), or perhaps the output from adding a `console.log(props);` before line 26;

**Comment by Binerax** [comment]
Error from console is TypeError: Cannot read properties of undefined (reading 'guild_id')

**Comment by Kyuuhachi** [comment]
I'm not sure what exactly would cause the issue, but here's a sizeable rewrite of the plugin, hopefully that makes it more stable. Could you try it and see?

**Comment by Binerax** [comment]
Plugin now crashes just trying to load a channel even with message logger off. With error **guildId is not defined**. Apologies if I somehow just installed incorrectly. But I have checked and it looks right.

**Comment by Kyuuhachi** [comment]
Hm, I may be stupid. I blame 3am. This, then? Sorry for the trouble.

**Comment by Binerax** [comment]
Can confirm it is fixed and works with the message logger now. Thank you for the fast fixes!

**Comment by Binerax** [comment]
Should be noted that it does work but is incorrect about the member being in the server (while in the message logger logs, it is correct everywhere else), just wanted to note that down. Don't expect that to be fixed if it is even possible. Thanks again!

**Comment by Kyuuhachi** [comment]
I don't think there's much I can do about that — I check if the channel the message is in is in a guild, and if so, check if the send of the message is a member of that guild. If that gives incorrect results, that must be because MLE gives incorrect parameters, which isn't anything I can do anything about.
