### ISSUE TITLE
Anammox patch outdated

### ISSUE THREAD

**Issue by verticalsync** [Kyuuhachi/VencordPlugins#9]
title

`/(\w+)=\(0,\w+.useCategoryNitroLockedStates\)\(\w+,\w+,(\w+)\)/ `

and

`/\{section:\i\.SectionTypes\.HEADER,label:\i\.default\.Messages\.BILLING_SETTINGS\},.*?\{section:\i\.SectionTypes\.DIVIDER\},/ `

**Comment by Kyuuhachi** [comment]
Should be fixed by aa50af2.
